<?php
/**
 * Author: Patrik Šíma <programator@patriksima.cz>
 * Licence: MIT
 */

@ini_set("auto_detect_line_endings", true);

function usage()
{
    global $argv;
    print 'Usage: '.$argv[0].' [-d] delimiter [-e] enclosure -t table csv_file'.PHP_EOL;
    exit(1);
}

function error()
{
    $error = error_get_last();
    //print $error['message'].PHP_EOL;
    exit(1);
}

$options = getopt("d::e::t:", array("d::"=>"","e::"=>"","t:"=>"table:"));

if ($argc-count($options) <= 1) {
    usage();
}

$table = (isset($options['t'])) ? $options['t'] : $options['table'];
$delimiter = (isset($options['d'])) ? $options['d'] : ',';
$enclosure = (isset($options['e'])) ? $options['e'] : '"';
$csvfile = array_pop($argv);

$fhandle = fopen($csvfile, 'r');
if ($fhandle === FALSE) {
    error();
}

while(($header=fgetcsv($fhandle,0,$delimiter,$enclosure))!==FALSE) {
    if (is_null($header[0])) {
        continue;
    } else {
        break;
    }
}

while(($tmp=fgetcsv($fhandle,0,$delimiter,$enclosure))!==FALSE) {
    if (is_null($tmp[0])) {
        continue;
    }
    print 'INSERT INTO '.$table.' ('.join(',',array_map(function($i){return '`'.$i.'`';},$header)).') VALUES ('.join(',',array_map(function($i){return "'".$i."'";},$tmp)).');'.PHP_EOL;
}

fclose($fhandle);

print '-- generated by patriksima.cz/csv2sql'.PHP_EOL;